# Generated by Django 5.1.4 on 2025-07-22 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reviews', serialize=False, to='Pyrestaurant.restaurant')),
                ('customer', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='Pyrestaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(default=0)),
                ('resturant_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pyrestaurant.review')),
            ],
        ),
    ]
