# Generated by Django 5.1.4 on 2025-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='order_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
