# Generated by Django 5.1.4 on 2025-07-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrestaurant', '0002_alter_customers_order_no'),
        ('Pyrestaurant', '0002_alter_restaurant_rating'),
    ]

    operations = [
    ]
