# Generated by Django 5.1.4 on 2025-07-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyrestaurant', '0003_merge_20250723_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
    ]
